<?php
/**
 * PIT Solutions
 *
 * NOTICE OF LICENSE
 * This source file is licenced under Webshop Extensions software license.
 * Once you have purchased the software with PIT Solutions AG or one of its
 * authorised resellers and provided that you comply with the conditions of this contract,
 * PIT Solutions AG grants you a non-exclusive license, unlimited in time for the usage of
 * the software in the manner of and for the purposes specified in the documentation according
 * to the subsequent regulations.
 *
 * @category Pits
 * @package  Pits_VoiceSearch
 * @author   Pit Solutions Pvt. Ltd.
 * @copyright Copyright (c) 2022 PIT Solutions AG. (www.pitsolutions.ch)
 * @license https://www.webshopextension.com/en/licence-agreement/
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var $locale \Magento\Search\ViewModel\ViewSearch */
$locale = $block->getData('voiceSearch');
$title = $block->getData('title') ?: __('Voice Search');
?>

<button id="voice-search-trigger"
        class="action primary voice-search"
        type="button"
        title="<?= $block->escapeHtmlAttr($title) ?>"
        data-mage-init='{
            "voiceSearch":{
                "locale": "<?= str_replace("_","-",$locale->getLocale())?>"
            }
        }'>
    <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('Pits_VoiceSearch::images/voice_icon.svg') ?>" >
</button>
